"""del oncascade for reviews

Revision ID: 155567d1f08a
Revises: 5439de03a414
Create Date: 2022-06-19 13:17:20.882137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155567d1f08a'
down_revision = '5439de03a414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reviews_user_id_users', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_book_id_books', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_book_id_books'), 'reviews', 'books', ['book_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_book_id_books'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_book_id_books', 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_reviews_user_id_users', 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
