"""del full_desk from books

Revision ID: 41cdf8c1adb0
Revises: 155567d1f08a
Create Date: 2022-06-19 19:51:15.964181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41cdf8c1adb0'
down_revision = '155567d1f08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_book_genre_book_id_books', 'book_genre', type_='foreignkey')
    op.drop_constraint('fk_book_genre_genre_id_genres', 'book_genre', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_genre_genre_id_genres'), 'book_genre', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(op.f('fk_book_genre_book_id_books'), 'book_genre', 'books', ['book_id'], ['id'])
    op.drop_column('books', 'full_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('full_desc', mysql.TEXT(), nullable=False))
    op.drop_constraint(op.f('fk_book_genre_book_id_books'), 'book_genre', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_genre_genre_id_genres'), 'book_genre', type_='foreignkey')
    op.create_foreign_key('fk_book_genre_genre_id_genres', 'book_genre', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_book_genre_book_id_books', 'book_genre', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
