"""add rule del cascade

Revision ID: 5439de03a414
Revises: c25185e0cb07
Create Date: 2022-06-15 17:50:04.773431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5439de03a414'
down_revision = 'c25185e0cb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_book_genre_genre_id_genres', 'book_genre', type_='foreignkey')
    op.drop_constraint('fk_book_genre_book_id_books', 'book_genre', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_genre_book_id_books'), 'book_genre', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_book_genre_genre_id_genres'), 'book_genre', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_images_book_id_books', 'images', type_='foreignkey')
    op.create_foreign_key(op.f('fk_images_book_id_books'), 'images', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_reviews_user_id_users', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_book_id_books', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_book_id_books'), 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_role_id_roles'), 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_role_id_roles'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_book_id_books'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_book_id_books', 'reviews', 'books', ['book_id'], ['id'])
    op.create_foreign_key('fk_reviews_user_id_users', 'reviews', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_images_book_id_books'), 'images', type_='foreignkey')
    op.create_foreign_key('fk_images_book_id_books', 'images', 'books', ['book_id'], ['id'])
    op.drop_constraint(op.f('fk_book_genre_genre_id_genres'), 'book_genre', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_genre_book_id_books'), 'book_genre', type_='foreignkey')
    op.create_foreign_key('fk_book_genre_book_id_books', 'book_genre', 'books', ['book_id'], ['id'])
    op.create_foreign_key('fk_book_genre_genre_id_genres', 'book_genre', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
