"""add delete on cascade

Revision ID: 6d4946031d82
Revises: 41cdf8c1adb0
Create Date: 2022-06-19 22:57:27.834538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4946031d82'
down_revision = '41cdf8c1adb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_book_genre_genre_id_genres', 'book_genre', type_='foreignkey')
    op.drop_constraint('fk_book_genre_book_id_books', 'book_genre', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_genre_book_id_books'), 'book_genre', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_book_genre_genre_id_genres'), 'book_genre', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.add_column('books', sa.Column('full_desc', sa.Text(), nullable=False))
    op.drop_constraint('fk_reviews_user_id_users', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_book_id_books', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_book_id_books'), 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_book_id_books'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_book_id_books', 'reviews', 'books', ['book_id'], ['id'])
    op.create_foreign_key('fk_reviews_user_id_users', 'reviews', 'users', ['user_id'], ['id'])
    op.drop_column('books', 'full_desc')
    op.drop_constraint(op.f('fk_book_genre_genre_id_genres'), 'book_genre', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_genre_book_id_books'), 'book_genre', type_='foreignkey')
    op.create_foreign_key('fk_book_genre_book_id_books', 'book_genre', 'books', ['book_id'], ['id'])
    op.create_foreign_key('fk_book_genre_genre_id_genres', 'book_genre', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
