"""del full_desk from books

Revision ID: faf57c068620
Revises: 6d4946031d82
Create Date: 2022-06-19 23:07:36.320513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faf57c068620'
down_revision = '6d4946031d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'full_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('full_desc', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
